### ISSUE TITLE
Plugin metadata incomplete with kotlin

### ISSUE THREAD

**Issue by mattmess1221** [SpongePowered/SpongeGradle#11]
I have a plugin using kotlin, but the generated mcmod.info is not complete. It only has name, modid, version, and description.

The plugin I'm building is here. https://github.com/killjoy1221/NoClip

**Comment by Zidane** [comment]
This should be re-opened on the API as it is handling the generation of the mcmod.info.

**Comment by mattmess1221** [comment]
The api works fine. The file kapt generates is in
/build/tmp/kapt3/classes/main and is what I expect it to do.

**Comment by Zidane** [comment]
@kashike

See above.

**Comment by kashike** [comment]
@killjoy1221 After looking at this a bit more, I'm not sure if there's a real good way to handle this. If you've got a suggestion, feel free to give it - or send a pull request, if you like.

Relevant:
- https://github.com/SpongePowered/SpongeGradle/blob/master/src/main/groovy/org/spongepowered/gradle/meta/GenerateMetadata.groovy
- https://github.com/JetBrains/kotlin/tree/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle

**Comment by mattmess1221** [comment]
It was caused by kapt itself actually. I was told that I needed the kotlin-kapt plugin in order for the annotation processor to work, but it was a lie. Annotation processing works just fine with just the kotlin plugin.

Additionally, it looks like compileJava takes care kotlin files as well.

**Comment by mattmess1221** [comment]
Actually, that seemed to be a fluke. I got it to work by adding these lines to my buildscript.
```gradle
compileKotlin.dependsOn generateMetadata
kapt {
    processors += 'org.spongepowered.plugin.processor.PluginProcessor'
    arguments {
        arg 'extraMetadataFiles', generateMetadata.target
        arg 'metadataOutputFile', generateMetadata.target
    }
}
afterEvaluate { tasks.kaptKotlin.outputs.upToDateWhen { false } }
```

For some reason, I think the kaptKotlin task is created in afterEvaluate.

**Comment by Aaron1011** [comment]
Can we re-open this? It's still an issue when trying to use SpongeAPI with Kotlin

**Comment by kashike** [comment]
Pull requests are welcome.

**Comment by zml2008** [comment]
This issue is no longer applicable to SpongeGradle 2.0.0+
