### ISSUE TITLE
Allow specification of jar to upload (instead of configuration)

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeGradle#17]
It would be very useful to be able to directly select the jar/artifact/task that creates the artifact to upload.

I know you can specify the configuration, but in order to select the correct jar, you have to do some ugly hacking with adding a different signing task and some other weird stuff, as can be seen in the Nucleus build script: https://github.com/NucleusPowered/Nucleus/blob/520803fc4c609572298722a8ce834e17633f7404/build.gradle#L287-L305

I think the CurseForge-Plugin does it really well. The only thing is I'm not sure how hard it is to get the signature of a jar when using a task as the source.

**Comment by zml2008** [comment]
Not relevant as of #56
