### ISSUE TITLE
generateMetadata doesn't work in multi-moduled project

### ISSUE THREAD

**Issue by GlassSpirit** [SpongePowered/SpongeGradle#20]
When gradle project is multi-moduled, generateMetadata only takes info from build.gradle file and ignores @Plugin annotation and mcmod.info inside resources

**Comment by stephan-gh** [comment]
What does "multi-moduled" mean? Do you have an example project?

If you are talking about subprojects, then SpongeGradle will always apply to the project it is applied on. So if you have plugins in subprojects, you need to apply SpongeGradle to the subprojects.

**Comment by GlassSpirit** [comment]
Yes, subprojects. You can look at [this repo](https://github.com/Sponge-RPG-dev/NT-RPG).
It has 3 subprojects, sponge plugin is applied to Plugin, but generated mcmod.info in build jar only contains info from build.gradle file of Plugin.

**Comment by gabizou** [comment]
This is supported with how it's been set up as a bundle meta.
