### ISSUE TITLE
[Bug] Index sponge 7.0.0

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/SpongeGradle#30]
https://pastes.dev/uMFkBWwC3W
Raw: https://bytebin.lucko.me/uMFkBWwC3W

`org.gradle.status=release, org.spongepowered.api-target=8.0.0`

```
Could not find net.minecrell:terminalconsoleappender:1.0.0-SNAPSHOT.
Required by:
    project : > org.spongepowered:spongevanilla:1.12-7.0.0-BETA-307
```

**Comment by zml2008** [comment]
build.gradle and gradle version please

**Comment by SettingDust** [comment]
> build.gradle and gradle version please

Error when `runServer`
https://pastes.dev/cV3kfJv6yW

```
spongeApiVersion = 8.0.0
```
