### ISSUE TITLE
Failed to read version manifest

### ISSUE THREAD

**Issue by AuroraLS3** [SpongePowered/SpongeGradle#41]
Hello,
my plugin started failing to build yesterday according to Github Actions.

I have not changed any sponge related code in the last 2 weeks, so I think it has something to do with either sponge dependency or the related gradle plugins.

Following build error occurs during configuration phase:
```
> Configure project :sponge
SpongePowered Plugin 'GRADLE' Toolset Version '2.0.2'
SpongePowered Vanilla 'GRADLE' Toolset Version '0.2'
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':sponge'.
> Failed to read version manifest
```
Using gradle version 7.4.2

Here is my build.gradle if it helps https://github.com/plan-player-analytics/Plan/blob/master/Plan/sponge/build.gradle (`spongeVersion` is `spongeVersion = "8.1.0"` and `fullVersion` is `fullVersion = "5.5 build 1760"`)

What could be causing this?

**Comment by Lignium** [comment]
You need to upgrade VanillaGradle to 0.2.1-SNAPSHOT version

**Comment by AuroraLS3** [comment]
What plugin repository are the snapshot versions in? - the build didn't find that version

```
* What went wrong:
Plugin [id: 'org.spongepowered.gradle.vanilla', version: '0.2.1-SNAPSHOT'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.spongepowered.gradle.vanilla:org.spongepowered.gradle.vanilla.gradle.plugin:0.2.1-SNAPSHOT')
  Searched in the following repositories:
    Fabric(https://maven.fabricmc.net/)
    MavenRepo
    Gradle Central Plugin Repository
```

**Comment by Lignium** [comment]
Should be in the SpongePowered repository. The question is, does Gradle see this repository?

**Comment by AuroraLS3** [comment]
Thank you, adding sponge repository to plugin repositories has resolved the issues.
