### ISSUE TITLE
The sortClassFields task doesn't work well with multiline fields.

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeGradle#6]
The `sortClassFields` task generates the newlines wrongly when you use multiline fields.
For example: https://github.com/SpongePowered/SpongeAPI/commit/9c80503ca4acbec9f8f41b94b3041fa4c5edaa96#diff-d14fd72dcfa14fbd217ec11b5069e2f0R99

**Comment by Deamon5550** [comment]
I'm about 99.9% certain that that was a copy-paste error not the sort fields task.

Edit: oh you just mean the spacing derp.
