### ISSUE TITLE
`plugin-0.0.0-all.jar` file from `shadowJar` is not being used

### ISSUE THREAD

**Issue by choyunjin** [SpongePowered/SpongeGradle#87]
I have a plugin with some dependencies, so I need to make a fat jar file(`plugin-0.0.0-all.jar`) with `shadowJar`. However, the `runServer` task doesn't uses the fat jar file but the original jar file(`plugin-0.0.0.jar`) and `NoClassDefFoundError` occurs.

**Comment by zml2008** [comment]
Which shadow plugin?

**Comment by choyunjin** [comment]
I'm using `com.gradleup.shadow` version `8.3.0`.

**Comment by zml2008** [comment]
Ah, we probably need to update SG for the new plugin ID.
